# These are supported funding model platforms

github: [tuanle96]
patreon: earnorm
open_collective: earnorm
ko_fi: earnorm
liberapay: earnorm
issuehunt: earnorm
custom: [ 'https://earnorm.dev/sponsor' ]

