# Database Configuration
database_backend: mongodb
database_uri: mongodb://localhost:27018/earnbase?retryWrites=true&retryReads=true
database_name: earnbase
database_username: # optional
database_password: # optional
database_min_pool_size: 5
database_max_pool_size: 20
database_pool_timeout: 30
database_max_lifetime: 3600 # 1 hour
database_idle_timeout: 300 # 5 minutes
database_ssl: false
database_ssl_ca: # optional
database_ssl_cert: # optional
database_ssl_key: # optional

# Database Connection Options
database_options:
  server_selection_timeout_ms: 5000
  connect_timeout_ms: 10000
  socket_timeout_ms: 20000
  retry_writes: true
  retry_reads: true
  w: 1
  j: true

# Redis Configuration
redis_host: localhost
redis_port: 6379
redis_db: 0
redis_min_pool_size: 5
redis_max_pool_size: 20
redis_pool_timeout: 30

# Version
version: 1.0.0

# Event Configuration
event_enabled: true
event_queue: earnorm:events
event_batch_size: 100
